// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AccountHolderDbContext))]
    partial class AccountHolderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountHolderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.HasKey("AccountNumber");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Models.AccountHolder", b =>
                {
                    b.Property<string>("AccountHolderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountHolderId");

                    b.ToTable("accountHolder");
                });

            modelBuilder.Entity("Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountHolderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountDetailsAccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountHolderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountHolderId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressDetailsAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InitialAmount")
                        .HasColumnType("float");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("AccountDetailsAccountNumber");

                    b.HasIndex("AccountHolderId")
                        .IsUnique();

                    b.HasIndex("AccountHolderId1");

                    b.HasIndex("AddressDetailsAddressId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Models.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("ReceiverAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.HasOne("Models.Account", "AccountDetails")
                        .WithMany()
                        .HasForeignKey("AccountDetailsAccountNumber");

                    b.HasOne("Models.AccountHolder", null)
                        .WithOne("CustomerDetails")
                        .HasForeignKey("Models.Customer", "AccountHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.AccountHolder", null)
                        .WithMany("CustomerDetailss")
                        .HasForeignKey("AccountHolderId1");

                    b.HasOne("Models.Address", "AddressDetails")
                        .WithMany()
                        .HasForeignKey("AddressDetailsAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountDetails");

                    b.Navigation("AddressDetails");
                });

            modelBuilder.Entity("Models.AccountHolder", b =>
                {
                    b.Navigation("CustomerDetails")
                        .IsRequired();

                    b.Navigation("CustomerDetailss");
                });
#pragma warning restore 612, 618
        }
    }
}
